import http from "k6/http";
import { check, sleep } from "k6";
import { Rate, Trend, Counter } from "k6/metrics";

// Custom metrics
export const errorRate = new Rate("custom_error_rate");
export const responseTime = new Trend("custom_response_time");
export const requestCounter = new Counter("custom_requests");

// Load-test configuration
export const options = {

    stages: [
        // Warm up
        { duration: "10s", target: 10 },

        // Increase traffic
        { duration: "20s", target: 25 },

        // Medium load
        { duration: "30s", target: 50 },

        // Heavy load
        { duration: "30s", target: 100 },

        // Peak load
        { duration: "30s", target: 200 },

        // Reduce traffic
        { duration: "20s", target: 50 },

        // Stop
        { duration: "10s", target: 0 }
    ],

    thresholds: {

        // Less than 1% failed HTTP requests
        http_req_failed: ["rate<0.01"],

        // 95% of requests should finish below 500 ms
        http_req_duration: ["p(95)<500"],

        // 99% should finish below 1 second
        "http_req_duration{expected_response:true}": [
            "p(99)<1000"
        ],

        // Custom error rate
        custom_error_rate: ["rate<0.01"]
    }
};


// ==========================================================
// TEST DATA
// ==========================================================

const notificationPayload = JSON.stringify({

    recipient: "test@example.com",

    subject: "Kafka Load Test",

    message: "This is a notification generated by k6.",

    type: "EMAIL"

});


// ==========================================================
// HTTP HEADERS
// ==========================================================

const params = {

    headers: {

        "Content-Type": "application/json",

        "Accept": "application/json"

    },

    tags: {

        name: "notification-api"

    }

};


// ==========================================================
// MAIN TEST
// ==========================================================

export default function () {

    /*
     * IMPORTANT:
     *
     * k6 is running inside Docker.
     *
     * Therefore use:
     *
     * http://nginx/...
     *
     * NOT:
     *
     * http://localhost:8080/...
     */

    //const url = "http://nginx/api/notifications";
    const url = "https://sandboxerp.shakti.org.bd:8070/api/Home/internallogin?username=19910&password=123456";
    //const url = "https://sandboxerp.shakti.org.bd:8070/api/KYC/membersearch";


    // ------------------------------------------------------
    // POST notification
    // ------------------------------------------------------

    const response = http.post(

        url,

        notificationPayload,

        params

    );


    // ------------------------------------------------------
    // Metrics
    // ------------------------------------------------------

    requestCounter.add(1);

    responseTime.add(response.timings.duration);


    // ------------------------------------------------------
    // Check response
    // ------------------------------------------------------

    const success = check(response, {

        "status is 200": (r) => r.status === 200,

        "status is 201": (r) => r.status === 201,

        "response time < 500ms":
            (r) => r.timings.duration < 500,

        "response body exists":
            (r) => r.body && r.body.length > 0

    });


    // Record errors

    errorRate.add(!success);


    // Small delay between requests

    sleep(1);
}

// export default function () {

//     const response = http.get(
//         "https://sandboxerp.shakti.org.bd:8070/api/Home/internallogin?username=19910&password=123456"
//     );

//     check(response, {
//         "HTTP status is 200": (r) => r.status === 200
//     });

//     sleep(1);
// }